import { defineStore } from "pinia";

export const useTraitsStore = defineStore("traits", () => {
  const physique = {
    label: "Physique",
    sheet: {
      id: "physique",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Athletic",
      "Brawny",
      "Corpulent",
      "Delicate",
      "Gaunt",
      "Hulking",
      "Lanky",
      "Ripped",
      "Rugged",
      "Scrawny",
      "Short",
      "Sinewy",
      "Slender",
      "Flabby",
      "Statuesque",
      "Stout",
      "Tiny",
      "Towering",
      "Willowy",
      "Wiry",
    ],
  };
  const face = {
    label: "Face",
    sheet: {
      id: "face",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Bloated",
      "Blunt",
      "Bony",
      "Chiseled",
      "Delicate",
      "Elongated",
      "Patrician",
      "Pinched",
      "Hawkish",
      "Broken",
      "Impish",
      "Narrow",
      "Ratlike",
      "Round",
      "Sunken",
      "Sharp",
      "Soft",
      "Square",
      "Wide",
      "Wolfish",
    ],
  };
  const skin = {
    label: "Skin",
    sheet: {
      id: "skin",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Battle Scar",
      "Birthmark",
      "Burn Scar",
      "Dark",
      "Makeup",
      "Oily",
      "Pale",
      "Perfect",
      "Pierced",
      "Pockmarked",
      "Reeking",
      "Tattooed",
      "Rosy",
      "Rough",
      "Sallow",
      "Sunburned",
      "Tanned",
      "War Paint",
      "Weathered",
      "Whip Scar",
    ],
  };
  const hair = {
    label: "Hair",
    sheet: {
      id: "hair",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Bald",
      "Braided",
      "Bristly",
      "Cropped",
      "Curly",
      "Disheveled",
      "Dreadlocks",
      "Filthy",
      "Frizzy",
      "Greased",
      "Limp",
      "Long",
      "Luxurious",
      "Mohawk",
      "Oily",
      "Ponytail",
      "Silky",
      "Topknot",
      "Wavy",
      "Wispy",
    ],
  };
  const clothing = {
    label: "Clothing",
    sheet: {
      id: "clothing",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Antique",
      "Bloody",
      "Ceremonial",
      "Decorated",
      "Eccentric",
      "Elegant",
      "Fashionable",
      "Filthy",
      "Flamboyant",
      "Stained",
      "Foreign",
      "Frayed",
      "Frumpy",
      "Livery",
      "Oversized",
      "Patched",
      "Perfumed",
      "Rancid",
      "Torn",
      "Undersized",
    ],
  };
  const virtue = {
    label: "Virtue",
    sheet: {
      id: "virtue",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Ambitious",
      "Cautious",
      "Courageous",
      "Courteous",
      "Curious",
      "Disciplined",
      "Focused",
      "Generous",
      "Gregarious",
      "Honest",
      "Honorable",
      "Humble",
      "Idealistic",
      "Just",
      "Loyal",
      "Merciful",
      "Righteous",
      "Serene",
      "Stoic",
      "Tolerant",
    ],
  };
  const vice = {
    label: "Vice",
    sheet: {
      id: "vice",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Aggressive",
      "Arrogant",
      "Bitter",
      "Cowardly",
      "Cruel",
      "Deceitful",
      "Flippant",
      "Gluttonous ",
      "Greedy",
      "Irascible",
      "Lazy",
      "Nervous",
      "Prejudiced",
      "Reckless",
      "Rude",
      "Suspicious",
      "Vain",
      "Vengeful",
      "Wasteful",
      "Whiny",
    ],
  };
  const speech = {
    label: "Speech",
    sheet: {
      id: "speech",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Blunt",
      "Booming",
      "Breathy",
      "Cryptic",
      "Drawling",
      "Droning",
      "Flowery",
      "Formal",
      "Gravelly",
      "Hoarse",
      "Mumbling",
      "Precise",
      "Quaint",
      "Rambling",
      "Rapid-fire",
      "Dialect",
      "Slow",
      "Squeaky",
      "Stuttering",
      "Whispery",
    ],
  };
  const background = {
    label: "Background",
    sheet: {
      id: "background",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Alchemist",
      "Beggar",
      "Butcher",
      "Burglar",
      "Charlatan",
      "Cleric",
      "Cook",
      "Cultist",
      "Gambler",
      "Herbalist",
      "Magician",
      "Mariner",
      "Mercenary",
      "Merchant",
      "Outlaw",
      "Performer",
      "Pickpocket",
      "Smuggler",
      "Student",
      "Tracker",
    ],
  };
  const misfortune = {
    label: "Misfortune",
    sheet: {
      id: "misfortune",
      type: "string",
    },
    roll: {
      weighted: false,
      count: 1,
    },
    items: [
      "Abandoned",
      "Addicted",
      "Blackmailed",
      "Condemned",
      "Cursed",
      "Defrauded",
      "Demoted",
      "Discredited",
      "Disowned",
      "Exiled",
      "Framed",
      "Haunted",
      "Kidnapped",
      "Mutilated",
      "Poor",
      "Pursued",
      "Rejected",
      "Replaced",
      "Robbed",
      "Suspected",
    ],
  };
  const alignment = {
    label: "Alignment",
    sheet: {
      id: "alignment",
      type: "string",
    },
    roll: {
      weighted: {
        min: 1,
        max: 20,
        valueType: "string",
      },
      count: 1,
    },
    items: [
      {
        results: [1, 2, 3, 4, 5],
        value: "Law",
      },
      {
        results: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        value: "Neutrality",
      },
      {
        results: [16, 17, 18, 19, 20],
        value: "Chaos",
      },
    ],
  };
  return {
    physique,
    face,
    skin,
    hair,
    clothing,
    virtue,
    vice,
    speech,
    background,
    misfortune,
    alignment,
  };
});
